on: [push]
jobs:
  repro:
    strategy:
      matrix:
        name:
          - foo
        include:
          - name: bar
            os: ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - run: echo bug
        shell: bash
